# Generated by Django 5.2.6 on 2025-09-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_analyzer", "0002_chatconversation_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video_id", models.CharField(max_length=100)),
                ("system_prompt", models.TextField()),
                ("message_history", models.JSONField(default=list)),
                ("initial_analysis_done", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
