# Generated by Django 5.2.6 on 2025-09-29 20:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_analyzer", "0003_videoconversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(default=uuid.uuid4, max_length=50, unique=True),
                ),
                ("max_videos", models.IntegerField(default=5)),
                ("videos_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
