# Generated by Django 5.2.6 on 2025-10-18 20:49

import video_analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_analyzer", "0003_videoconversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=video_analyzer.models.generate_trial_code,
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("max_videos", models.IntegerField(default=5)),
                ("videos_used", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
