# Generated by Django 5.2.6 on 2025-09-29 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_analyzer", "0004_triallink"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoconversation",
            name="trial_link",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="video_analyzer.triallink",
            ),
        ),
    ]
