# Generated by Django 5.0.2 on 2025-05-04 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_document",
                    models.FileField(upload_to="documents/original/"),
                ),
                (
                    "processed_document",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/processed/"
                    ),
                ),
                ("old_logo", models.ImageField(upload_to="logos/old/")),
                ("new_logo", models.ImageField(upload_to="logos/new/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
