# Generated by Django 5.0.2 on 2025-05-04 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_processor", "0002_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
