# Generated by Django 5.0.2 on 2025-05-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("document_processor", "0003_alter_feedback_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="processeddocument",
            name="delete_running",
            field=models.BooleanField(default=False),
        ),
    ]
